Use dummy audio driver when mixer init fails
On a system that does not have a sound device, initialisation of
pygame.mixer does fail, the body of the activity is not rendered, and
the Sugar launcher remains visible.

Log shows error;

pygame.error: ALSA: Couldn't open audio device: No such file or directory

Catch exception and use the SDL dummy audio driver.

Credit for initial research to Abhijeet Dey <dey20405@gmail.com>

Fixes #20.